<?php
/**
 * AuditLogEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LogSentinel RESTful API
 *
 * Read more at https://logsentinel.com/docs
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AuditLogEntryTest Class Doc Comment
 *
 * @category    Class */
// * @description AuditLogEntry
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuditLogEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AuditLogEntry"
     */
    public function testAuditLogEntry()
    {

    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {

    }

    /**
     * Test attribute "actor_display_name"
     */
    public function testPropertyActorDisplayName()
    {

    }

    /**
     * Test attribute "actor_id"
     */
    public function testPropertyActorId()
    {

    }

    /**
     * Test attribute "actor_role"
     */
    public function testPropertyActorRole()
    {

    }

    /**
     * Test attribute "additional_params"
     */
    public function testPropertyAdditionalParams()
    {

    }

    /**
     * Test attribute "application_id"
     */
    public function testPropertyApplicationId()
    {

    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {

    }

    /**
     * Test attribute "entity_id"
     */
    public function testPropertyEntityId()
    {

    }

    /**
     * Test attribute "entity_type"
     */
    public function testPropertyEntityType()
    {

    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {

    }

    /**
     * Test attribute "previous_entry_id"
     */
    public function testPropertyPreviousEntryId()
    {

    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {

    }

    /**
     * Test attribute "timestamp_group_hash"
     */
    public function testPropertyTimestampGroupHash()
    {

    }

    /**
     * Test attribute "timestamp_group_size"
     */
    public function testPropertyTimestampGroupSize()
    {

    }

    /**
     * Test attribute "timestamp_time"
     */
    public function testPropertyTimestampTime()
    {

    }

    /**
     * Test attribute "timestamp_token_id"
     */
    public function testPropertyTimestampTokenId()
    {

    }

}
