<?php
/**
 * VerificationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LogSentinel RESTful API
 *
 * Read more at https://logsentinel.com/docs
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VerificationTest Class Doc Comment
 *
 * @category    Class */
// * @description Verification
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VerificationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Verification"
     */
    public function testVerification()
    {

    }

    /**
     * Test attribute "application_id"
     */
    public function testPropertyApplicationId()
    {

    }

    /**
     * Test attribute "attempted_hash"
     */
    public function testPropertyAttemptedHash()
    {

    }

    /**
     * Test attribute "audit_log_entry_id"
     */
    public function testPropertyAuditLogEntryId()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "failure"
     */
    public function testPropertyFailure()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

}
