<?php
/**
 * AuditlogcontrollerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LogSentinel RESTful API
 *
 * Read more at https://logsentinel.com/docs
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AuditlogcontrollerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AuditlogcontrollerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for logAuthActionUsingPOST
     *
     * Log an authentication event with the option to pass actor public key and signature.
     *
     */
    public function testLogAuthActionUsingPOST()
    {

    }

    /**
     * Test case for logSimpleUsingPOST
     *
     * Log an event by providing just the body without any additional metadata. The body can be fully encrypted.
     *
     */
    public function testLogSimpleUsingPOST()
    {

    }

    /**
     * Test case for logStandardActionUsingPOST
     *
     * Log an event by providing full details.
     *
     */
    public function testLogStandardActionUsingPOST()
    {

    }

    /**
     * Test case for logUsingPOST
     *
     * Log an event by a given actor.
     *
     */
    public function testLogUsingPOST()
    {

    }

    /**
     * Test case for searchUsingGET
     *
     * Search logged entries.
     *
     */
    public function testSearchUsingGET()
    {

    }

    /**
     * Test case for verifyUsingPOST
     *
     * Verify whether a given hash is present, indicating that the log is intact.
     *
     */
    public function testVerifyUsingPOST()
    {

    }

}
