<?php
/**
 * HashcontrollerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LogSentinel RESTful API
 *
 * Read more at https://logsentinel.com/docs
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * HashcontrollerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HashcontrollerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for getHashableContentForAuthActionUsingPOST
     *
     * Get the hash of a request for auth actions.
     *
     */
    public function testGetHashableContentForAuthActionUsingPOST()
    {

    }

    /**
     * Test case for getHashableContentForStandardActionUsingPOST
     *
     * Get the hash of a request for standard actions.
     *
     */
    public function testGetHashableContentForStandardActionUsingPOST()
    {

    }

    /**
     * Test case for getHashableContentSimpleUsingPOST
     *
     * Get the hash of a request without any additional metadata (including encrypted request bodies).
     *
     */
    public function testGetHashableContentSimpleUsingPOST()
    {

    }

    /**
     * Test case for getHashableContentUsingPOST
     *
     * Get the hash of a request for simple (minimial metadata) actions.
     *
     */
    public function testGetHashableContentUsingPOST()
    {

    }

}
